export const FEATURE_REGISTRY_EXAMPLES = {
  futureTestFeature: {
    id: 'future-test-feature',
    name: 'Future test feature',
    category: 'test',
    shortDescription: 'Fixture used to verify missing feature detection.',
    purpose: 'Ensure new capabilities cannot be marked as available before they are explainable.',
    howItWorks: 'The registry detects the feature and requires a definition before certification.',
    inputs: ['nom de la feature', 'détection par registre'],
    outputs: ['draft non certifié', 'échec de validation si status AVAILABLE'],
    security: ['Aucun privilege ajouté à la documentation seule.'],
    limitations: ['La functionalité reste DRAFT tant qu’elle n’est pas validée.'],
    prerequisites: ['Détection par le module et validation du registry.'],
    relatedFeatures: ['settings-models'],
    status: 'DRAFT',
    available: false,
    verified: false,
    technicalReferences: ['src/content/featureRegistry.ts'],
    routes: [],
    sourceModules: ['src/content/featureRegistry.ts'],
    sourceTests: ['scripts/test-feature-registry.mjs'],
    documentationVersion: 'draft',
  },
};
