// Media Studio V1 — non-destructive media projects (assets, tracks, clips) and
// FFmpeg export jobs.
//
// Reuses what exists: FFmpeg / ffprobe (same `spawn('ffmpeg', …)` convention as
// whisper.js), process-tree.js (tree kill, no orphan), Root Policy V1
// `MEDIA_TRANSCODE` (capability MEDIA.TRANSCODE already granted to the `media`
// module — enforced before EVERY process start), the F2 job vocabulary.
//
// Process safety: fixed binaries, structured argv, shell:false, every path is
// generated by Docteur inside the studio folder (never a client path), every
// filter value is a number or an internal label. Media files are never modified:
// edits change the project JSON; exports write NEW files.
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { killProcessTree } from './process-tree.js';

export const LIMITS = Object.freeze({
  maxAssetBytes: 1024 * 1024 * 1024,
  chunkBytes: 8 * 1024 * 1024,
  maxAssetsPerProject: 200,
  maxClipsPerProject: 500,
  maxProjectMs: 3 * 60 * 60_000,
  minClipMs: 100,
  defaultImageMs: 3_000,
  maxImageMs: 60 * 60_000,
  maxFadeMs: 30_000,
  maxVolume: 2,
  exportTimeoutMs: 30 * 60_000,
  exportStallMs: 2 * 60_000,
  probeTimeoutMs: 30_000,
  uploadTtlMs: 60 * 60_000,
});
export const RESOLUTIONS = Object.freeze({ '640x360': [640, 360], '1280x720': [1280, 720], '1920x1080': [1920, 1080], '1080x1920': [1080, 1920] });
export const FPS_CHOICES = Object.freeze([24, 25, 30]);
export const JOB_STATUS = Object.freeze({ QUEUED: 'QUEUED', RUNNING: 'RUNNING', COMPLETED: 'COMPLETED', FAILED: 'FAILED', CANCELLED: 'CANCELLED' });
const FINAL_JOB = new Set([JOB_STATUS.COMPLETED, JOB_STATUS.FAILED, JOB_STATUS.CANCELLED]);

export class StudioError extends Error {
  constructor(code, message, status = 400) { super(message); this.code = code; this.status = status; }
}

const isId = (v) => typeof v === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(v);
const nowIso = () => new Date().toISOString();
const clampInt = (v, min, max) => Math.min(Math.max(Math.round(Number(v)), min), max);
const num = (v) => Number.isFinite(Number(v)) ? Number(v) : NaN;

// ── File type (decided by content, never by the client name) ────────────────

export function sniffMedia(head) {
  const b = head;
  const ascii = (s, e) => Buffer.from(b.subarray(s, e)).toString('latin1');
  if (b.length >= 8 && b[0] === 0x89 && ascii(1, 4) === 'PNG') return { kind: 'image', ext: 'png' };
  if (b.length >= 3 && b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff) return { kind: 'image', ext: 'jpg' };
  if (b.length >= 12 && ascii(0, 4) === 'RIFF' && ascii(8, 12) === 'WEBP') return { kind: 'image', ext: 'webp' };
  if (b.length >= 6 && /^GIF8[79]a$/.test(ascii(0, 6))) return { kind: 'image', ext: 'gif' };
  if (b.length >= 12 && ascii(0, 4) === 'RIFF' && ascii(8, 12) === 'WAVE') return { kind: 'audio', ext: 'wav' };
  if (b.length >= 4 && ascii(0, 4) === 'OggS') return { kind: 'audio', ext: 'ogg' };
  if (b.length >= 4 && ascii(0, 4) === 'fLaC') return { kind: 'audio', ext: 'flac' };
  if (b.length >= 3 && ascii(0, 3) === 'ID3') return { kind: 'audio', ext: 'mp3' };
  if (b.length >= 2 && b[0] === 0xff && (b[1] & 0xe0) === 0xe0) return { kind: 'audio', ext: 'mp3' };
  if (b.length >= 4 && b[0] === 0x1a && b[1] === 0x45 && b[2] === 0xdf && b[3] === 0xa3) return { kind: 'video', ext: 'webm' };
  if (b.length >= 12 && ascii(4, 8) === 'ftyp') {
    const brand = ascii(8, 12);
    if (/^M4A /.test(brand)) return { kind: 'audio', ext: 'm4a' };
    return { kind: 'video', ext: brand.startsWith('qt') ? 'mov' : 'mp4' };
  }
  return null;
}

export function safeDisplayName(name) {
  const base = String(name ?? '').normalize('NFC').split(/[\\/]/).pop() ?? '';
  const clean = base.replace(/[\u0000-\u001f\u007f<>:"|?*]/g, '').replace(/^[.\s]+|[.\s]+$/g, '').slice(0, 120);
  return clean && !/^(con|prn|aux|nul|com\d|lpt\d)(\..*)?$/i.test(clean) ? clean : 'média';
}

// ── Project model ─────────────────────────────────────────────────────────────

export function defaultProject({ id, name, at = nowIso() }) {
  return {
    id, name: safeDisplayName(name || 'Projet média'), version: 1,
    settings: { resolution: '1280x720', fps: 30 },
    assets: [],
    tracks: [
      { id: 'V1', kind: 'video', name: 'Vidéo', muted: false, volume: 1 },
      { id: 'A1', kind: 'audio', name: 'Audio', muted: false, volume: 1 },
    ],
    clips: [],
    exportConfig: { format: 'mp4', crf: 23, preset: 'veryfast' },
    createdAt: at, updatedAt: at,
  };
}

const assetOf = (project, id) => project.assets.find(a => a.id === id) ?? null;
export const clipDurationMs = (clip) => clip.outMs - clip.inMs;

/** Video clips laid back to back (the sequence) + total duration. */
export function computeTimeline(project) {
  let t = 0;
  const video = project.clips.filter(c => c.trackId === 'V1').map(c => { const start = t; t += clipDurationMs(c); return { ...c, startMs: start }; });
  const audio = project.clips.filter(c => c.trackId === 'A1').map(c => ({ ...c }));
  return { video, audio, durationMs: t };
}

/** Validates the whole project; every value is bounded. Throws StudioError. */
export function validateProject(p) {
  if (!RESOLUTIONS[p.settings?.resolution]) throw new StudioError('INVALID_SETTINGS', 'Résolution non prise en charge.');
  if (!FPS_CHOICES.includes(p.settings?.fps)) throw new StudioError('INVALID_SETTINGS', 'Cadence non prise en charge.');
  if (p.clips.length > LIMITS.maxClipsPerProject) throw new StudioError('TOO_MANY_CLIPS', 'Trop de clips dans le projet.');
  for (const c of p.clips) {
    const asset = assetOf(p, c.assetId);
    if (!asset) throw new StudioError('ASSET_NOT_FOUND', 'Un clip référence un média absent.');
    if (!['V1', 'A1'].includes(c.trackId)) throw new StudioError('INVALID_TRACK', 'Piste inconnue.');
    if (c.trackId === 'V1' && asset.kind === 'audio') throw new StudioError('INVALID_TRACK', 'Un média audio va sur la piste audio.');
    if (c.trackId === 'A1' && !asset.hasAudio) throw new StudioError('INVALID_TRACK', 'Ce média n’a pas de son.');
    if (!(c.inMs >= 0 && c.outMs - c.inMs >= LIMITS.minClipMs)) throw new StudioError('INVALID_TRIM', `Un clip doit durer au moins ${LIMITS.minClipMs} ms.`);
    if (asset.kind !== 'image' && c.outMs > asset.durationMs + 1) throw new StudioError('INVALID_TRIM', 'Le point de sortie dépasse la durée du média.');
    if (asset.kind === 'image' && c.outMs > LIMITS.maxImageMs) throw new StudioError('INVALID_TRIM', 'Image trop longue.');
    if (!(c.volume >= 0 && c.volume <= LIMITS.maxVolume)) throw new StudioError('INVALID_VOLUME', 'Volume entre 0 et 200 %.');
    if (!(c.fadeInMs >= 0 && c.fadeOutMs >= 0 && c.fadeInMs + c.fadeOutMs <= clipDurationMs(c) && c.fadeInMs <= LIMITS.maxFadeMs && c.fadeOutMs <= LIMITS.maxFadeMs)) throw new StudioError('INVALID_FADE', 'Fondus incompatibles avec la durée du clip.');
    if (c.trackId === 'A1' && !(c.startMs >= 0 && c.startMs <= LIMITS.maxProjectMs)) throw new StudioError('INVALID_POSITION', 'Position audio invalide.');
  }
  if (computeTimeline(p).durationMs > LIMITS.maxProjectMs) throw new StudioError('PROJECT_TOO_LONG', 'Projet trop long (3 h maximum).');
  return p;
}

const newClip = (asset, trackId, extra = {}) => ({
  id: crypto.randomUUID(), trackId, assetId: asset.id,
  inMs: 0, outMs: asset.kind === 'image' ? LIMITS.defaultImageMs : asset.durationMs,
  volume: 1, muted: false, fadeInMs: 0, fadeOutMs: 0, ...(trackId === 'A1' ? { startMs: 0 } : {}), ...extra,
});

/** Pure timeline edit: returns a NEW project (validated); never touches media files. */
export function applyEdit(project, op) {
  const p = structuredClone(project);
  const clipIndex = (id) => { const i = p.clips.findIndex(c => c.id === id); if (i < 0) throw new StudioError('CLIP_NOT_FOUND', 'Clip introuvable.', 404); return i; };
  switch (op?.op) {
    case 'add': {
      const asset = assetOf(p, op.assetId);
      if (!asset) throw new StudioError('ASSET_NOT_FOUND', 'Média introuvable.', 404);
      const trackId = op.trackId === 'A1' ? 'A1' : 'V1';
      const extra = trackId === 'A1' ? { startMs: Number.isFinite(Number(op.startMs)) ? clampInt(op.startMs, 0, LIMITS.maxProjectMs) : computeTimeline(p).audio.reduce((end, c) => Math.max(end, c.startMs + clipDurationMs(c)), 0) } : {};
      p.clips.push(newClip(asset, trackId, extra));
      break;
    }
    case 'trim': {
      const c = p.clips[clipIndex(op.clipId)];
      const asset = assetOf(p, c.assetId);
      const inMs = asset.kind === 'image' ? 0 : num(op.inMs);
      const outMs = num(op.outMs);
      if (!Number.isFinite(inMs) || !Number.isFinite(outMs)) throw new StudioError('INVALID_TRIM', 'Points d’entrée / sortie invalides.');
      c.inMs = Math.round(inMs); c.outMs = Math.round(outMs);
      c.fadeInMs = Math.min(c.fadeInMs, Math.floor(clipDurationMs(c) / 2)); c.fadeOutMs = Math.min(c.fadeOutMs, Math.floor(clipDurationMs(c) / 2));
      break;
    }
    case 'split': {
      const i = clipIndex(op.clipId);
      const c = p.clips[i];
      const at = Math.round(num(op.atMs)); // relative to the clip start
      if (!(at >= LIMITS.minClipMs && clipDurationMs(c) - at >= LIMITS.minClipMs)) throw new StudioError('INVALID_SPLIT', `Point de coupe trop près d’un bord (${LIMITS.minClipMs} ms minimum de chaque côté).`);
      const second = { ...c, id: crypto.randomUUID(), inMs: c.inMs + at, fadeInMs: 0, ...(c.trackId === 'A1' ? { startMs: c.startMs + at } : {}) };
      c.outMs = c.inMs + at; c.fadeOutMs = 0;
      p.clips.splice(i + 1, 0, second);
      break;
    }
    case 'reorder': {
      const i = clipIndex(op.clipId);
      const c = p.clips[i];
      if (c.trackId !== 'V1') throw new StudioError('INVALID_REORDER', 'Seuls les clips vidéo se réordonnent ; déplacez les clips audio dans le temps.');
      const video = p.clips.filter(x => x.trackId === 'V1');
      const to = clampInt(op.toIndex, 0, video.length - 1);
      const reordered = video.filter(x => x.id !== c.id);
      reordered.splice(to, 0, c);
      p.clips = [...reordered, ...p.clips.filter(x => x.trackId !== 'V1')];
      break;
    }
    case 'move': {
      const c = p.clips[clipIndex(op.clipId)];
      if (c.trackId !== 'A1') throw new StudioError('INVALID_MOVE', 'Seuls les clips audio se placent librement ; réordonnez les clips vidéo.');
      c.startMs = Math.round(num(op.startMs));
      break;
    }
    case 'update': {
      const c = p.clips[clipIndex(op.clipId)];
      for (const key of ['volume', 'fadeInMs', 'fadeOutMs']) if (op[key] !== undefined) c[key] = key === 'volume' ? Math.round(num(op[key]) * 100) / 100 : Math.round(num(op[key]));
      if (op.muted !== undefined) c.muted = op.muted === true;
      if (assetOf(p, c.assetId).kind === 'image' && op.durationMs !== undefined) { c.inMs = 0; c.outMs = Math.round(num(op.durationMs)); }
      break;
    }
    case 'delete': p.clips.splice(clipIndex(op.clipId), 1); break;
    case 'track': {
      const t = p.tracks.find(x => x.id === op.trackId);
      if (!t) throw new StudioError('INVALID_TRACK', 'Piste inconnue.');
      if (op.muted !== undefined) t.muted = op.muted === true;
      if (op.volume !== undefined) { const v = num(op.volume); if (!(v >= 0 && v <= LIMITS.maxVolume)) throw new StudioError('INVALID_VOLUME', 'Volume entre 0 et 200 %.'); t.volume = Math.round(v * 100) / 100; }
      break;
    }
    case 'settings': {
      if (op.resolution !== undefined) p.settings.resolution = String(op.resolution);
      if (op.fps !== undefined) p.settings.fps = Number(op.fps);
      if (op.name !== undefined) p.name = safeDisplayName(op.name);
      break;
    }
    default: throw new StudioError('UNKNOWN_EDIT', `Modification inconnue : ${op?.op ?? '(vide)'}.`);
  }
  p.updatedAt = nowIso();
  return validateProject(p);
}

// ── Export plan (pure): argv only, numbers and internal labels ───────────────

const sec = (ms) => (Math.max(0, ms) / 1000).toFixed(3);

export function buildExportArgs(project, { assetPath, outputPath }) {
  validateProject(project);
  const { video, audio, durationMs } = computeTimeline(project);
  if (video.length === 0) throw new StudioError('EMPTY_TIMELINE', 'Ajoutez au moins un clip vidéo ou image sur la piste vidéo.');
  const [W, H] = RESOLUTIONS[project.settings.resolution];
  const F = project.settings.fps;
  const vTrack = project.tracks.find(t => t.id === 'V1');
  const aTrack = project.tracks.find(t => t.id === 'A1');
  const args = ['-hide_banner', '-nostdin', '-loglevel', 'error'];
  const filters = [];
  let input = 0;
  const concat = [];
  video.forEach((c, k) => {
    const asset = assetOf(project, c.assetId);
    const D = clipDurationMs(c);
    if (asset.kind === 'image') args.push('-loop', '1', '-framerate', String(F), '-t', sec(D), '-i', assetPath(asset));
    else args.push('-ss', sec(c.inMs), '-t', sec(D), '-i', assetPath(asset));
    const vi = input++;
    filters.push(`[${vi}:v]scale=${W}:${H}:force_original_aspect_ratio=decrease,pad=${W}:${H}:(ow-iw)/2:(oh-ih)/2:color=black,setsar=1,fps=${F},format=yuv420p,trim=duration=${sec(D)},setpts=PTS-STARTPTS[v${k}]`);
    const gain = (vTrack.muted || c.muted) ? 0 : c.volume * vTrack.volume;
    const fades = [c.fadeInMs > 0 ? `afade=t=in:st=0:d=${sec(c.fadeInMs)}` : null, c.fadeOutMs > 0 ? `afade=t=out:st=${sec(D - c.fadeOutMs)}:d=${sec(c.fadeOutMs)}` : null].filter(Boolean);
    if (asset.kind === 'video' && asset.hasAudio && gain > 0) {
      filters.push(`[${vi}:a]aresample=48000,aformat=sample_fmts=fltp:channel_layouts=stereo,apad,atrim=duration=${sec(D)},asetpts=PTS-STARTPTS,volume=${gain.toFixed(2)}${fades.map(f => `,${f}`).join('')}[a${k}]`);
    } else {
      args.push('-f', 'lavfi', '-t', sec(D), '-i', 'anullsrc=channel_layout=stereo:sample_rate=48000');
      const si = input++;
      filters.push(`[${si}:a]aformat=sample_fmts=fltp:channel_layouts=stereo,atrim=duration=${sec(D)},asetpts=PTS-STARTPTS[a${k}]`);
    }
    concat.push(`[v${k}][a${k}]`);
  });
  filters.push(`${concat.join('')}concat=n=${video.length}:v=1:a=1[vseq][aseq]`);
  const mixed = [];
  if (!aTrack.muted) {
    audio.filter(c => !c.muted && c.volume > 0 && c.startMs < durationMs).forEach((c, m) => {
      const asset = assetOf(project, c.assetId);
      const D = clipDurationMs(c);
      args.push('-ss', sec(c.inMs), '-t', sec(D), '-i', assetPath(asset));
      const ai = input++;
      const fades = [c.fadeInMs > 0 ? `,afade=t=in:st=0:d=${sec(c.fadeInMs)}` : '', c.fadeOutMs > 0 ? `,afade=t=out:st=${sec(D - c.fadeOutMs)}:d=${sec(c.fadeOutMs)}` : ''].join('');
      filters.push(`[${ai}:a]aresample=48000,aformat=sample_fmts=fltp:channel_layouts=stereo,atrim=duration=${sec(D)},asetpts=PTS-STARTPTS,volume=${(c.volume * aTrack.volume).toFixed(2)}${fades},adelay=${Math.round(c.startMs)}|${Math.round(c.startMs)}[b${m}]`);
      mixed.push(`[b${m}]`);
    });
  }
  filters.push(mixed.length ? `[aseq]${mixed.join('')}amix=inputs=${mixed.length + 1}:duration=first:dropout_transition=0:normalize=0[aout]` : '[aseq]anull[aout]');
  const { crf, preset } = project.exportConfig;
  args.push(
    '-filter_complex', filters.join(';'),
    '-map', '[vseq]', '-map', '[aout]',
    '-c:v', 'libx264', '-preset', preset, '-crf', String(crf), '-pix_fmt', 'yuv420p', '-r', String(F),
    '-c:a', 'aac', '-b:a', '160k', '-ar', '48000',
    '-t', sec(durationMs), '-movflags', '+faststart',
    '-progress', 'pipe:1', '-nostats', '-y', outputPath,
  );
  return { args, durationMs };
}

// ── Service ──────────────────────────────────────────────────────────────────

/** Streaming SHA-256 (a 1 GB asset is never loaded in memory). */
/** Provenance shown to the user only (never fetched by the server): a file chosen by the user, or a link opened in
 *  the Media Reader (http(s) only, no credentials, bounded). */
export function uploadSource(origin) {
  if (origin?.type !== 'media-reader') return { type: 'upload' };
  try {
    const u = new URL(String(origin.url ?? ''));
    if (!['http:', 'https:'].includes(u.protocol) || u.username || u.password || u.href.length > 2048) return { type: 'media-reader' };
    return { type: 'media-reader', url: u.href };
  } catch { return { type: 'media-reader' }; }
}

export function sha256File(file) {
  return new Promise((resolve, reject) => {
    const hash = crypto.createHash('sha256');
    fs.createReadStream(file).on('data', d => hash.update(d)).on('error', reject).on('end', () => resolve(hash.digest('hex')));
  });
}

function runProcess(spawnImpl, bin, args, { timeoutMs }) {
  return new Promise((resolve, reject) => {
    let out = ''; let err = '';
    const proc = spawnImpl(bin, args, { shell: false, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] });
    const timer = setTimeout(() => { killProcessTree(proc); reject(new StudioError('PROBE_TIMEOUT', 'Analyse du média trop longue.', 422)); }, timeoutMs);
    proc.stdout.on('data', d => { if (out.length < 2_000_000) out += d; });
    proc.stderr.on('data', d => { if (err.length < 20_000) err += d; });
    proc.on('error', e => { clearTimeout(timer); reject(new StudioError('FFMPEG_UNAVAILABLE', `FFmpeg indisponible (${e.code ?? e.message}).`, 503)); });
    proc.on('close', code => { clearTimeout(timer); code === 0 ? resolve(out) : reject(Object.assign(new StudioError('CORRUPT_MEDIA', 'Média illisible ou corrompu.', 422), { detail: err.slice(-500) })); });
  });
}

export function parseProbe(json, sniffed) {
  let data;
  try { data = JSON.parse(json); } catch { throw new StudioError('CORRUPT_MEDIA', 'Média illisible ou corrompu.', 422); }
  const streams = Array.isArray(data.streams) ? data.streams : [];
  const v = streams.find(s => s.codec_type === 'video' && s.disposition?.attached_pic !== 1);
  const a = streams.find(s => s.codec_type === 'audio');
  const duration = Math.round(Number(data.format?.duration ?? v?.duration ?? a?.duration ?? 0) * 1000);
  const kind = sniffed.kind === 'image' ? 'image' : (v ? 'video' : (a ? 'audio' : null));
  if (!kind) throw new StudioError('CORRUPT_MEDIA', 'Aucun flux audio ou vidéo exploitable.', 422);
  if (kind !== 'image' && !(duration >= LIMITS.minClipMs)) throw new StudioError('CORRUPT_MEDIA', 'Durée du média illisible.', 422);
  if (kind === 'video' && sniffed.kind === 'audio') return { kind: 'audio', durationMs: duration, hasVideo: false, hasAudio: true, width: null, height: null };
  return {
    kind, durationMs: kind === 'image' ? null : duration,
    hasVideo: kind !== 'audio', hasAudio: kind !== 'image' && Boolean(a),
    width: v?.width ?? null, height: v?.height ?? null,
  };
}

/**
 * deps: { rootDir, store, enforce(request), resolveDocteurImage(id) → absolute path, ffmpegBin, ffprobeBin, spawnImpl, logger }
 */
export function createMediaStudioService({ rootDir, store, enforce, resolveDocteurImage = null, ffmpegBin = 'ffmpeg', ffprobeBin = 'ffprobe', spawnImpl = spawn, logger = null, exportTimeoutMs = LIMITS.exportTimeoutMs, exportStallMs = LIMITS.exportStallMs }) {
  const uploads = new Map(); // uploadId → { projectId, name, size, received, file, startedAt }
  let running = null;        // { jobId, proc, cancelled, interrupted }
  let stopped = false;       // server stopping: nothing new starts
  const dirOf = (projectId) => path.join(rootDir, 'projects', projectId);
  const assetPath = (projectId) => (asset) => path.join(dirOf(projectId), 'assets', asset.file);
  const ensure = (dir) => fs.mkdirSync(dir, { recursive: true });
  const transcodeAllowed = (engine) => enforce({ action: 'MEDIA_TRANSCODE', module: 'media', trustDomain: 'MEDIA', context: { engine, networkClass: 'none' } });

  function requireProject(id) {
    if (!isId(id)) throw new StudioError('INVALID_ID', 'Identifiant invalide.');
    const p = store.getProject(id);
    if (!p) throw new StudioError('PROJECT_NOT_FOUND', 'Projet introuvable.', 404);
    return p;
  }
  const save = (p) => { store.saveProject(p); return p; };
  const view = (p) => ({ project: p, timeline: computeTimeline(p), jobs: store.listJobs(p.id) });

  async function probe(file, sniffed) {
    transcodeAllowed('ffprobe'); // Root Policy before any process start
    const out = await runProcess(spawnImpl, ffprobeBin, ['-v', 'error', '-print_format', 'json', '-show_format', '-show_streams', file], { timeoutMs: LIMITS.probeTimeoutMs });
    return parseProbe(out, sniffed);
  }

  async function addAssetFromFile(project, tmpFile, { name, source }) {
    if (project.assets.length >= LIMITS.maxAssetsPerProject) throw new StudioError('TOO_MANY_ASSETS', 'Trop de médias dans ce projet.');
    const fd = fs.openSync(tmpFile, 'r');
    const head = Buffer.alloc(64);
    fs.readSync(fd, head, 0, 64, 0);
    fs.closeSync(fd);
    const sniffed = sniffMedia(head);
    if (!sniffed) throw new StudioError('UNSUPPORTED_MEDIA', 'Type non pris en charge (vidéo MP4/MOV/WebM, audio MP3/WAV/OGG/M4A/FLAC, image PNG/JPEG/WebP/GIF) — vérifié sur le contenu.', 415);
    const meta = await probe(tmpFile, sniffed);
    const id = crypto.randomUUID();
    const file = `${id}.${sniffed.ext}`;
    ensure(path.join(dirOf(project.id), 'assets'));
    const sha256 = await sha256File(tmpFile);
    fs.renameSync(tmpFile, path.join(dirOf(project.id), 'assets', file));
    const asset = { id, name: safeDisplayName(name), file, kind: meta.kind, size: fs.statSync(path.join(dirOf(project.id), 'assets', file)).size, durationMs: meta.durationMs, hasVideo: meta.hasVideo, hasAudio: meta.hasAudio, width: meta.width, height: meta.height, sha256, source, addedAt: nowIso() };
    const next = { ...project, assets: [...project.assets, asset], updatedAt: nowIso() };
    save(next);
    return { asset, ...view(next) };
  }

  // ── export queue (one at a time) ──
  function pump() {
    if (running || stopped) return;
    const job = store.nextQueuedJob();
    if (!job) return;
    void runJob(job);
  }

  async function runJob(job) {
    const project = store.getProject(job.projectId);
    running = { jobId: job.id, proc: null, cancelled: false };
    const outDir = path.join(dirOf(job.projectId), 'exports');
    const outputFile = path.join(outDir, `${job.id}.mp4`);
    const finish = (status, patch = {}) => {
      store.updateJob(job.id, { status, finishedAt: nowIso(), ...patch });
      running = null;
      setImmediate(pump);
    };
    try {
      if (!project) throw new StudioError('PROJECT_NOT_FOUND', 'Projet introuvable.', 404);
      transcodeAllowed('ffmpeg'); // Root Policy before any process start
      ensure(outDir);
      const { args, durationMs } = buildExportArgs(project, { assetPath: assetPath(project.id), outputPath: outputFile });
      store.updateJob(job.id, { status: JOB_STATUS.RUNNING, startedAt: nowIso(), durationMs, progress: 0 });
      const proc = spawnImpl(ffmpegBin, args, { shell: false, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] });
      running.proc = proc;
      let stderr = '';
      let lastProgress = Date.now();
      let buffer = '';
      proc.stdout.on('data', chunk => {
        buffer += chunk;
        let nl;
        while ((nl = buffer.indexOf('\n')) >= 0) {
          const line = buffer.slice(0, nl).trim();
          buffer = buffer.slice(nl + 1);
          const m = line.match(/^out_time_(?:us|ms)=(\d+)$/);
          if (m && durationMs > 0) {
            const pct = Math.min(99, Math.floor((Number(m[1]) / 1000 / durationMs) * 100));
            store.updateJob(job.id, { progress: pct });
            lastProgress = Date.now();
          }
        }
      });
      proc.stderr.on('data', d => { if (stderr.length < 8_000) stderr += d; });
      const code = await new Promise((resolve) => {
        const timeout = setTimeout(() => { stderr += '\n[timeout]'; killProcessTree(proc); }, exportTimeoutMs);
        const stall = setInterval(() => { if (Date.now() - lastProgress > exportStallMs) { stderr += '\n[stalled]'; killProcessTree(proc); } }, Math.min(5_000, exportStallMs));
        proc.on('error', e => { clearTimeout(timeout); clearInterval(stall); stderr += `\n${e.code ?? e.message}`; resolve(-1); });
        proc.on('close', c => { clearTimeout(timeout); clearInterval(stall); resolve(c); });
      });
      if (running?.cancelled) {
        fs.rmSync(outputFile, { force: true });
        return running.interrupted ? finish(JOB_STATUS.FAILED, { error: 'interrupted_by_restart' }) : finish(JOB_STATUS.CANCELLED, { error: 'cancelled_by_user' });
      }
      const size = fs.existsSync(outputFile) ? fs.statSync(outputFile).size : 0;
      if (code !== 0 || size === 0) {
        fs.rmSync(outputFile, { force: true });
        const reason = /\[timeout\]/.test(stderr) ? 'Export trop long (délai dépassé).' : /\[stalled\]/.test(stderr) ? 'Export bloqué (aucune progression).' : `FFmpeg a échoué : ${stderr.replaceAll(rootDir, '<studio>').trim().split('\n').slice(-3).join(' ').slice(0, 400) || `code ${code}`}`;
        return finish(JOB_STATUS.FAILED, { error: reason });
      }
      return finish(JOB_STATUS.COMPLETED, { progress: 100, outputFile: path.basename(outputFile), outputSize: size });
    } catch (err) {
      fs.rmSync(outputFile, { force: true });
      const message = err?.code === 'ROOT_POLICY_DENIED' || err?.name === 'RootPolicyDeniedError' ? `Root Policy : ${err.message}` : (err?.message ?? 'Erreur inconnue');
      logger?.warn?.({ jobId: job.id, err: message }, 'media studio export failed');
      return finish(JOB_STATUS.FAILED, { error: message.slice(0, 400) });
    }
  }

  return {
    LIMITS,
    createProject({ name } = {}) { return view(save(defaultProject({ id: crypto.randomUUID(), name }))); },
    listProjects() { return store.listProjects(); },
    getProject(id) { return view(requireProject(id)); },
    edit(id, op) { return view(save(applyEdit(requireProject(id), op))); },

    removeAsset(projectId, assetId) {
      const p = requireProject(projectId);
      const asset = assetOf(p, assetId);
      if (!asset) throw new StudioError('ASSET_NOT_FOUND', 'Média introuvable.', 404);
      if (p.clips.some(c => c.assetId === assetId)) throw new StudioError('ASSET_IN_USE', 'Ce média est utilisé dans la timeline : supprimez d’abord ses clips.', 409);
      fs.rmSync(assetPath(p.id)(asset), { force: true }); // Docteur's own copy only — never the user's original
      return view(save({ ...p, assets: p.assets.filter(a => a.id !== assetId), updatedAt: nowIso() }));
    },
    assetFile(projectId, assetId) {
      const p = requireProject(projectId);
      const asset = assetOf(p, assetId);
      if (!asset) throw new StudioError('ASSET_NOT_FOUND', 'Média introuvable.', 404);
      const file = assetPath(p.id)(asset);
      if (!fs.existsSync(file)) throw new StudioError('ASSET_FILE_MISSING', 'Le fichier de ce média est introuvable sur le disque.', 404);
      return { file, asset };
    },

    startUpload(projectId, { name, size, origin = null }) {
      requireProject(projectId);
      const total = Number(size);
      if (!Number.isInteger(total) || total <= 0) throw new StudioError('INVALID_SIZE', 'Taille de fichier invalide.');
      if (total > LIMITS.maxAssetBytes) throw new StudioError('FILE_TOO_LARGE', 'Fichier trop volumineux (1 Go maximum).', 413);
      for (const [id, u] of uploads) if (Date.now() - u.startedAt > LIMITS.uploadTtlMs) { fs.rmSync(u.file, { force: true }); uploads.delete(id); }
      const uploadId = crypto.randomUUID();
      ensure(path.join(rootDir, 'tmp'));
      const file = path.join(rootDir, 'tmp', `${uploadId}.part`);
      fs.writeFileSync(file, Buffer.alloc(0));
      uploads.set(uploadId, { projectId, name: safeDisplayName(name), size: total, received: 0, file, startedAt: Date.now(), source: uploadSource(origin) });
      return { uploadId, chunkBytes: LIMITS.chunkBytes };
    },
    appendChunk(uploadId, offset, bytes) {
      const u = isId(uploadId) ? uploads.get(uploadId) : null;
      if (!u) throw new StudioError('UPLOAD_NOT_FOUND', 'Envoi introuvable ou expiré.', 404);
      if (Number(offset) !== u.received) throw new StudioError('INVALID_OFFSET', `Morceau inattendu (attendu à l’octet ${u.received}).`, 409);
      if (bytes.length === 0 || bytes.length > LIMITS.chunkBytes) throw new StudioError('INVALID_CHUNK', 'Morceau invalide.');
      if (u.received + bytes.length > u.size) throw new StudioError('INVALID_CHUNK', 'Plus de données que la taille annoncée.');
      fs.appendFileSync(u.file, bytes);
      u.received += bytes.length;
      return { received: u.received, size: u.size };
    },
    async completeUpload(uploadId, { sha256 = null } = {}) {
      const u = isId(uploadId) ? uploads.get(uploadId) : null;
      if (!u) throw new StudioError('UPLOAD_NOT_FOUND', 'Envoi introuvable ou expiré.', 404);
      uploads.delete(uploadId);
      try {
        if (u.received !== u.size) throw new StudioError('INCOMPLETE_UPLOAD', 'Envoi incomplet.');
        if (sha256) {
          const actual = await sha256File(u.file);
          if (actual !== String(sha256).toLowerCase()) throw new StudioError('CHECKSUM_MISMATCH', 'Somme de contrôle différente : fichier altéré pendant l’envoi.');
        }
        return await addAssetFromFile(requireProject(u.projectId), u.file, { name: u.name, source: u.source });
      } finally {
        fs.rmSync(u.file, { force: true });
      }
    },
    cancelUpload(uploadId) {
      const u = isId(uploadId) ? uploads.get(uploadId) : null;
      if (u) { fs.rmSync(u.file, { force: true }); uploads.delete(uploadId); }
      return { cancelled: Boolean(u) };
    },
    async importDocteurImage(projectId, imageId) {
      const project = requireProject(projectId);
      if (typeof resolveDocteurImage !== 'function') throw new StudioError('NOT_AVAILABLE', 'Import indisponible.', 503);
      const src = resolveDocteurImage(imageId); // validated by the image module (id format, inside its folder)
      if (!src || !fs.existsSync(src)) throw new StudioError('ASSET_NOT_FOUND', 'Image Docteur introuvable.', 404);
      ensure(path.join(rootDir, 'tmp'));
      const tmp = path.join(rootDir, 'tmp', `${crypto.randomUUID()}.part`);
      fs.copyFileSync(src, tmp);
      try { return await addAssetFromFile(project, tmp, { name: `image-${String(imageId).slice(0, 8)}`, source: { type: 'docteur-image', imageId } }); } finally { fs.rmSync(tmp, { force: true }); }
    },

    requestExport(projectId) {
      const p = requireProject(projectId);
      buildExportArgs(p, { assetPath: assetPath(p.id), outputPath: 'check.mp4' }); // validates the timeline before queueing
      const job = { id: crypto.randomUUID(), projectId, status: JOB_STATUS.QUEUED, createdAt: nowIso() };
      store.insertJob(job);
      setImmediate(pump);
      return store.getJob(job.id);
    },
    async cancelExport(jobId) {
      const job = isId(jobId) ? store.getJob(jobId) : null;
      if (!job) throw new StudioError('JOB_NOT_FOUND', 'Export introuvable.', 404);
      if (FINAL_JOB.has(job.status)) throw new StudioError('JOB_FINISHED', 'Cet export est déjà terminé.', 409);
      if (job.status === JOB_STATUS.QUEUED) { store.updateJob(job.id, { status: JOB_STATUS.CANCELLED, finishedAt: nowIso(), error: 'cancelled_by_user' }); return store.getJob(job.id); }
      if (running?.jobId === job.id) { running.cancelled = true; if (running.proc) await killProcessTree(running.proc); }
      return store.getJob(job.id);
    },
    getJob(jobId) { const j = isId(jobId) ? store.getJob(jobId) : null; if (!j) throw new StudioError('JOB_NOT_FOUND', 'Export introuvable.', 404); return j; },
    exportFile(jobId) {
      const job = this.getJob(jobId);
      if (job.status !== JOB_STATUS.COMPLETED || !job.outputFile) throw new StudioError('EXPORT_NOT_READY', 'Export non terminé.', 409);
      const file = path.join(dirOf(job.projectId), 'exports', job.outputFile);
      if (!fs.existsSync(file)) throw new StudioError('EXPORT_FILE_MISSING', "Le fichier exporté est introuvable sur le disque.", 404);
      return { file, job };
    },
    runningProcess() { return running?.proc ?? null; },

    /** Boot: nothing resumes by itself; interrupted jobs are reported. */
    recoverAfterRestart() {
      let n = 0;
      for (const job of store.listJobsByStatus([JOB_STATUS.RUNNING, JOB_STATUS.QUEUED])) {
        store.updateJob(job.id, { status: job.status === JOB_STATUS.RUNNING ? JOB_STATUS.FAILED : JOB_STATUS.CANCELLED, finishedAt: nowIso(), error: 'interrupted_by_restart' });
        n += 1;
      }
      fs.rmSync(path.join(rootDir, 'tmp'), { recursive: true, force: true });
      return { interrupted: n };
    },
    /** Server stop: tree-kill the running export (no orphan). */
    /** Server stop: the running export is reported as interrupted (written before the kill), queued ones wait for the next boot. */
    async shutdown() {
      stopped = true;
      if (!running) return;
      running.cancelled = true;
      running.interrupted = true;
      store.updateJob(running.jobId, { status: JOB_STATUS.FAILED, finishedAt: nowIso(), error: 'interrupted_by_restart' });
      if (running.proc) await killProcessTree(running.proc);
    },
  };
}
