// Professeur V2 (PROF-5) — Sport Coach exercise catalog (static, curated). Every entry declares what it NEEDS
// (equipment — all required, [] = none), WHERE it can be done, which body areas it LOADS, its complexity, technique
// cues, frequent mistakes, an easier / harder variant and equipment substitutes. Used to build the deterministic
// fallback program and to offer variants. Generic training information only — no medical content.

const L = { all: ['maison', 'salle', 'exterieur'], inside: ['maison', 'salle'], gym: ['salle'], out: ['exterieur'] };

export const EXERCISES = Object.freeze([
  // ── bas du corps (squat / fente) ──
  { id: 'chaise_murale', name: 'Chaise contre un mur', pattern: 'lower', type: 'duration', equipment: [], locations: L.inside, areas: ['genou'], complexity: 'basic', cues: ['Dos plaqué au mur', 'Genoux au-dessus des chevilles'], mistakes: ['Genoux qui rentrent', 'Bloquer la respiration'], easier: null, harder: 'squat_pdc', substitutes: [] },
  { id: 'squat_pdc', name: 'Squat au poids du corps', pattern: 'lower', type: 'reps', equipment: [], locations: L.all, areas: ['genou', 'hanche'], complexity: 'basic', cues: ['Pieds largeur d’épaules', 'Pousser les hanches en arrière', 'Talons au sol'], mistakes: ['Genoux qui rentrent', 'Dos arrondi'], easier: 'chaise_murale', harder: 'fentes', substitutes: [] },
  { id: 'squat_goblet_halteres', name: 'Squat goblet (haltère)', pattern: 'lower', type: 'reps', equipment: ['halteres'], locations: L.inside, areas: ['genou', 'hanche'], complexity: 'basic', cues: ['Haltère contre la poitrine', 'Descendre en gardant le buste droit'], mistakes: ['Talons qui décollent', 'Coudes qui tombent'], easier: 'squat_pdc', harder: 'split_squat_halteres', substitutes: ['squat_goblet_kettlebell', 'squat_pdc'] },
  { id: 'squat_goblet_kettlebell', name: 'Squat goblet (kettlebell)', pattern: 'lower', type: 'reps', equipment: ['kettlebell'], locations: L.inside, areas: ['genou', 'hanche'], complexity: 'basic', cues: ['Kettlebell tenue par les cornes', 'Buste droit'], mistakes: ['Talons qui décollent', 'Dos arrondi'], easier: 'squat_pdc', harder: 'split_squat_halteres', substitutes: ['squat_goblet_halteres', 'squat_pdc'] },
  { id: 'fentes', name: 'Fentes alternées', pattern: 'lower', type: 'reps', equipment: [], locations: L.all, areas: ['genou', 'hanche'], complexity: 'intermediate', cues: ['Grand pas', 'Genou arrière vers le sol', 'Buste droit'], mistakes: ['Genou avant qui dépasse fortement', 'Perte d’équilibre'], easier: 'squat_pdc', harder: 'split_squat_halteres', substitutes: ['squat_pdc'] },
  { id: 'split_squat_halteres', name: 'Split squat avec haltères', pattern: 'lower', type: 'reps', equipment: ['halteres'], locations: L.inside, areas: ['genou', 'hanche'], complexity: 'intermediate', cues: ['Position fendue stable', 'Descendre verticalement'], mistakes: ['Buste penché', 'Pied avant trop proche'], easier: 'fentes', harder: 'squat_barre', substitutes: ['fentes'] },
  { id: 'squat_barre', name: 'Squat barre (rack)', pattern: 'lower', type: 'reps', equipment: ['barre', 'rack'], locations: L.gym, areas: ['genou', 'hanche', 'dos'], complexity: 'advanced', cues: ['Barre stable sur le haut du dos', 'Gainage avant la descente', 'Sécurités du rack réglées'], mistakes: ['Dos qui s’arrondit en bas', 'Charge trop lourde pour la technique'], easier: 'squat_goblet_halteres', harder: null, substitutes: ['squat_goblet_halteres', 'squat_goblet_kettlebell', 'squat_pdc'] },
  // ── charnière de hanche ──
  { id: 'pont_fessier', name: 'Pont fessier', pattern: 'hinge', type: 'reps', equipment: [], locations: L.inside, areas: ['hanche'], complexity: 'basic', cues: ['Pousser dans les talons', 'Serrer les fessiers en haut'], mistakes: ['Cambrer le bas du dos', 'Monter trop vite'], easier: null, harder: 'souleve_roumain_halteres', substitutes: [] },
  { id: 'souleve_roumain_halteres', name: 'Soulevé de terre roumain (haltères)', pattern: 'hinge', type: 'reps', equipment: ['halteres'], locations: L.inside, areas: ['dos', 'hanche'], complexity: 'intermediate', cues: ['Dos neutre', 'Hanches vers l’arrière', 'Haltères près des jambes'], mistakes: ['Dos arrondi', 'Plier les genoux comme un squat'], easier: 'pont_fessier', harder: 'souleve_terre_barre', substitutes: ['swing_kettlebell', 'pont_fessier'] },
  { id: 'swing_kettlebell', name: 'Swing kettlebell', pattern: 'hinge', type: 'reps', equipment: ['kettlebell'], locations: L.inside, areas: ['dos', 'hanche'], complexity: 'intermediate', cues: ['Le mouvement vient des hanches', 'Bras relâchés'], mistakes: ['Lever avec les bras', 'Dos arrondi'], easier: 'pont_fessier', harder: null, substitutes: ['souleve_roumain_halteres', 'pont_fessier'] },
  { id: 'souleve_terre_barre', name: 'Soulevé de terre (barre)', pattern: 'hinge', type: 'reps', equipment: ['barre'], locations: L.gym, areas: ['dos', 'hanche'], complexity: 'advanced', cues: ['Barre au-dessus du milieu du pied', 'Dos neutre et gainé', 'Pousser le sol'], mistakes: ['Dos arrondi', 'Barre éloignée du corps'], easier: 'souleve_roumain_halteres', harder: null, substitutes: ['souleve_roumain_halteres', 'swing_kettlebell', 'pont_fessier'] },
  // ── poussée ──
  { id: 'pompes_inclinees', name: 'Pompes inclinées (mains surélevées)', pattern: 'push', type: 'reps', equipment: [], locations: L.all, areas: ['epaule', 'poignet'], complexity: 'basic', cues: ['Corps gainé en planche', 'Coudes à 45°'], mistakes: ['Hanches qui tombent', 'Coudes écartés à 90°'], easier: null, harder: 'pompes', substitutes: [] },
  { id: 'pompes', name: 'Pompes', pattern: 'push', type: 'reps', equipment: [], locations: L.all, areas: ['epaule', 'poignet', 'coude'], complexity: 'intermediate', cues: ['Gainage du début à la fin', 'Poitrine vers le sol'], mistakes: ['Hanches qui tombent', 'Amplitude incomplète'], easier: 'pompes_inclinees', harder: 'pompes_declinees', substitutes: ['pompes_inclinees'] },
  { id: 'pompes_declinees', name: 'Pompes déclinées (pieds surélevés)', pattern: 'push', type: 'reps', equipment: [], locations: L.all, areas: ['epaule', 'poignet', 'coude'], complexity: 'advanced', cues: ['Pieds surélevés stables', 'Gainage fort'], mistakes: ['Cambrure', 'Tête qui tombe'], easier: 'pompes', harder: null, substitutes: ['pompes'] },
  { id: 'developpe_halteres_banc', name: 'Développé couché haltères (banc)', pattern: 'push', type: 'reps', equipment: ['halteres', 'banc'], locations: L.inside, areas: ['epaule', 'coude'], complexity: 'intermediate', cues: ['Omoplates serrées', 'Descente contrôlée'], mistakes: ['Rebond sur la poitrine', 'Poignets cassés'], easier: 'pompes_inclinees', harder: 'developpe_couche_barre', substitutes: ['pompes', 'pompes_inclinees'] },
  { id: 'developpe_couche_barre', name: 'Développé couché barre (rack)', pattern: 'push', type: 'reps', equipment: ['barre', 'banc', 'rack'], locations: L.gym, areas: ['epaule', 'coude', 'poignet'], complexity: 'advanced', cues: ['Sécurités réglées ou partenaire', 'Barre au niveau du bas des pectoraux'], mistakes: ['Fesses qui décollent', 'Charge trop lourde'], easier: 'developpe_halteres_banc', harder: null, substitutes: ['developpe_halteres_banc', 'pompes'] },
  { id: 'developpe_epaules_halteres', name: 'Développé épaules haltères', pattern: 'push', type: 'reps', equipment: ['halteres'], locations: L.inside, areas: ['epaule', 'coude'], complexity: 'intermediate', cues: ['Gainage, côtes rentrées', 'Pousser au-dessus de la tête'], mistakes: ['Cambrer le dos', 'Hausser les épaules'], easier: 'pompes_inclinees', harder: null, substitutes: ['pompes_inclinees'] },
  // ── tirage ──
  { id: 'superman', name: 'Superman au sol', pattern: 'pull', type: 'reps', equipment: [], locations: L.inside, areas: ['dos'], complexity: 'basic', cues: ['Lever bras et jambes doucement', 'Regard vers le sol'], mistakes: ['Hyper-cambrer', 'Mouvement brusque'], easier: null, harder: 'rowing_bande', substitutes: [] },
  { id: 'rowing_bande', name: 'Rowing avec bande élastique', pattern: 'pull', type: 'reps', equipment: ['bandes'], locations: L.all, areas: ['dos', 'epaule'], complexity: 'basic', cues: ['Tirer les coudes vers l’arrière', 'Serrer les omoplates'], mistakes: ['Hausser les épaules', 'Tirer avec les bras seulement'], easier: 'superman', harder: 'rowing_halteres', substitutes: ['superman'] },
  { id: 'rowing_halteres', name: 'Rowing haltère un bras', pattern: 'pull', type: 'reps', equipment: ['halteres'], locations: L.inside, areas: ['dos', 'epaule'], complexity: 'basic', cues: ['Dos plat, appui stable', 'Coude vers la hanche'], mistakes: ['Rotation du buste', 'Dos arrondi'], easier: 'rowing_bande', harder: 'rowing_barre', substitutes: ['rowing_bande', 'superman'] },
  { id: 'rowing_barre', name: 'Rowing barre penché', pattern: 'pull', type: 'reps', equipment: ['barre'], locations: L.gym, areas: ['dos', 'epaule'], complexity: 'advanced', cues: ['Buste penché, dos neutre', 'Barre vers le nombril'], mistakes: ['Dos arrondi', 'Élan avec le buste'], easier: 'rowing_halteres', harder: null, substitutes: ['rowing_halteres', 'rowing_bande'] },
  // ── gainage ──
  { id: 'gainage_genoux', name: 'Planche sur les genoux', pattern: 'core', type: 'duration', equipment: [], locations: L.all, areas: ['epaule'], complexity: 'basic', cues: ['Alignement épaules-hanches-genoux'], mistakes: ['Fesses trop hautes'], easier: null, harder: 'planche', substitutes: [] },
  { id: 'dead_bug', name: 'Dead bug', pattern: 'core', type: 'reps', equipment: [], locations: L.inside, areas: [], complexity: 'basic', cues: ['Bas du dos collé au sol', 'Mouvement lent'], mistakes: ['Dos qui décolle', 'Aller trop vite'], easier: null, harder: 'planche', substitutes: [] },
  { id: 'planche', name: 'Planche (gainage)', pattern: 'core', type: 'duration', equipment: [], locations: L.all, areas: ['epaule', 'dos'], complexity: 'basic', cues: ['Corps aligné', 'Respirer normalement'], mistakes: ['Hanches qui tombent', 'Apnée'], easier: 'gainage_genoux', harder: 'planche_laterale', substitutes: ['dead_bug'] },
  { id: 'planche_laterale', name: 'Planche latérale', pattern: 'core', type: 'duration', equipment: [], locations: L.all, areas: ['epaule'], complexity: 'intermediate', cues: ['Hanches hautes', 'Coude sous l’épaule'], mistakes: ['Hanches qui tombent'], easier: 'planche', harder: null, substitutes: ['dead_bug'] },
  // ── cardio ──
  { id: 'marche_rapide', name: 'Marche rapide', pattern: 'cardio', type: 'duration', equipment: [], locations: L.out, areas: [], complexity: 'basic', cues: ['Rythme où l’on peut encore parler'], mistakes: ['Partir trop vite'], easier: null, harder: 'course_exterieur', substitutes: [] },
  { id: 'course_exterieur', name: 'Course à pied', pattern: 'cardio', type: 'duration', equipment: [], locations: L.out, areas: ['genou', 'cheville'], complexity: 'intermediate', cues: ['Foulée courte et souple', 'Allure conversation'], mistakes: ['Allure trop rapide', 'Attaque talon marquée'], easier: 'marche_rapide', harder: null, substitutes: ['marche_rapide'] },
  { id: 'velo', name: 'Vélo (endurance)', pattern: 'cardio', type: 'duration', equipment: ['velo'], locations: L.all, areas: [], complexity: 'basic', cues: ['Cadence régulière', 'Selle à bonne hauteur'], mistakes: ['Résistance trop forte'], easier: null, harder: null, substitutes: ['marche_rapide', 'montees_genoux'] },
  { id: 'tapis_course', name: 'Tapis de course', pattern: 'cardio', type: 'duration', equipment: ['tapis_de_course'], locations: L.inside, areas: ['genou', 'cheville'], complexity: 'basic', cues: ['Commencer en marchant', 'Ne pas se tenir aux barres'], mistakes: ['Vitesse trop élevée d’emblée'], easier: null, harder: null, substitutes: ['montees_genoux', 'marche_rapide'] },
  { id: 'montees_genoux', name: 'Montées de genoux sur place', pattern: 'cardio', type: 'duration', equipment: [], locations: L.all, areas: ['cheville', 'genou'], complexity: 'basic', cues: ['Rythme régulier', 'Atterrir sur l’avant du pied'], mistakes: ['Se pencher en arrière'], easier: 'step_touch', harder: 'jumping_jacks', substitutes: ['step_touch'] },
  { id: 'step_touch', name: 'Pas chassés sur place (sans impact)', pattern: 'cardio', type: 'duration', equipment: [], locations: L.all, areas: [], complexity: 'basic', cues: ['Bras actifs', 'Rester léger'], mistakes: ['Rythme trop lent'], easier: null, harder: 'montees_genoux', substitutes: [] },
  { id: 'jumping_jacks', name: 'Jumping jacks', pattern: 'cardio', type: 'duration', equipment: [], locations: L.all, areas: ['cheville', 'genou'], complexity: 'intermediate', cues: ['Réception souple'], mistakes: ['Réception jambes tendues'], easier: 'montees_genoux', harder: null, substitutes: ['step_touch'] },
  // ── mobilité ──
  { id: 'chat_vache', name: 'Chat-vache', pattern: 'mobility', type: 'reps', equipment: [], locations: L.inside, areas: [], complexity: 'basic', cues: ['Mouvement lent, vertèbre par vertèbre'], mistakes: ['Forcer l’amplitude'], easier: null, harder: null, substitutes: [] },
  { id: 'rotation_thoracique', name: 'Rotations thoraciques au sol', pattern: 'mobility', type: 'reps', equipment: [], locations: L.inside, areas: [], complexity: 'basic', cues: ['Suivre la main du regard', 'Bassin stable'], mistakes: ['Tourner le bassin'], easier: null, harder: null, substitutes: [] },
  { id: 'mobilite_hanches', name: 'Mobilité des hanches (90/90)', pattern: 'mobility', type: 'duration', equipment: [], locations: L.inside, areas: [], complexity: 'basic', cues: ['Buste grand', 'Respiration lente'], mistakes: ['Forcer dans la douleur'], easier: null, harder: null, substitutes: [] },
  { id: 'cercles_bras', name: 'Cercles de bras', pattern: 'mobility', type: 'reps', equipment: [], locations: L.all, areas: [], complexity: 'basic', cues: ['Amplitude progressive'], mistakes: ['Mouvement saccadé'], easier: null, harder: null, substitutes: [] },
  { id: 'mobilite_chevilles', name: 'Mobilité des chevilles', pattern: 'mobility', type: 'reps', equipment: [], locations: L.all, areas: [], complexity: 'basic', cues: ['Genou vers l’avant, talon au sol'], mistakes: ['Talon qui décolle'], easier: null, harder: null, substitutes: [] },
]);

export const EXERCISE_BY_ID = Object.freeze(Object.fromEntries(EXERCISES.map(e => [e.id, e])));

/** Warm-up and cool-down blocks — always feasible without equipment, generic and gentle. */
export const WARMUP = Object.freeze([
  { name: 'Mobilisation articulaire (nuque, épaules, hanches, chevilles)', duration_sec: 120 },
  { name: 'Cardio léger progressif (marche sur place, pas chassés)', duration_sec: 180 },
]);
export const COOLDOWN = Object.freeze([
  { name: 'Retour au calme : marche lente et respiration', duration_sec: 120 },
  { name: 'Étirements doux des muscles travaillés (sans douleur)', duration_sec: 180 },
]);
